### ISSUE TITLE
warp_options.cpp::parse misses to set papszWarpOptions

### ISSUE THREAD

**Issue by BergWerkGIS** [naturalatlas/node-gdal#109]
[warp_options.cpp](https://github.com/naturalatlas/node-gdal/blob/master/src/utils/warp_options.cpp) does not set [papszWarpOptions](http://www.gdal.org/structGDALWarpOptions.html#a0ed77f9917bb96c7a9aabd73d4d06e08).

Therefore it is not possible to e.g. use multiple threads for warping (`NUM_THREADS=ALL_CPUS`), which would significantly improve performance of [`gdal.reprojectImage`](http://naturalatlas.github.io/node-gdal/classes/gdal.html#method-reprojectImage).

**Comment by BergWerkGIS** [comment]
Verified!

Inserted `options->papszWarpOptions = additional_options.get();` [here](https://github.com/naturalatlas/node-gdal/blob/master/src/utils/warp_options.cpp#L84) and now  [`gdal.reprojectImage`](http://naturalatlas.github.io/node-gdal/classes/gdal.html#method-reprojectImage) maxes out my CPU.

**Comment by brandonreavis** [comment]
Whoops! Yeah that's all it should take! I can try throwing together a test to check for that and then we can push out a new release today. How urgent is the progress function issue? I agree that that would be slick, but I'm thinking that will be a bit too involved to get around to today.

**Comment by BergWerkGIS** [comment]
A new release including `papszWarpOptions` would be really helpful, if it could be done as soon as possible.

Progress function is not that pressing anymore, after `papszWarpOptions` are implemented, as this seriously cuts down on processing time.
Nevertheless, progress function would be nice to have, some time.

Another question: 
Would it be possible to duplicate the `-multi` switch of [gdalwarp](http://www.gdal.org/gdalwarp.html)?
This should reduce processing time even more.
`-multi` switch gets evaluated [here](https://github.com/OSGeo/gdal/blob/trunk/gdal/apps/gdalwarp.cpp#L1878-L1885), where it either branches to [`GDALWarpOperation::ChunkAndWarpMulti`](https://github.com/OSGeo/gdal/blob/trunk/gdal/alg/gdalwarpoperation.cpp#L834) or  [`GDALWarpOperation::ChunkAndWarpImage`](https://github.com/OSGeo/gdal/blob/trunk/gdal/alg/gdalwarpoperation.cpp#L669)

**Comment by brandonreavis** [comment]
Alright additional config options should work once it builds and the we release the next version.

About the `-multi` switch there would be two ways

1. Override the [`GDALReprojectImage()`](https://github.com/OSGeo/gdal/blob/67fd4d92f2e7afb604995c6e6846a61bfe3c36fd/gdal/alg/gdalwarper.cpp#L241-L243) method and add the optional `GDALWarpOperation::ChunkAndWarpMulti` in. It's a pretty simple convenience method so using an unofficial version of it wouldn't be too bad.

2. Expose the [`GDALWarpOperation`](http://www.gdal.org/classGDALWarpOperation.html) class which gives finer warping control including the `ChunkAndWarpMulti()` method.

My vote is the first option because it would be quick to do and easy for people to use. If in the future if someone needs methods like `ChunkAndWarpMulti()` or `WarpRegion()`, we can go ahead and expose that, but my guess is that that's unlikely to happen. You don't see any immediate use for these exposing these methods do you?

**Comment by brandonreavis** [comment]
Ended up going with the quick and easy solution for now.

**Comment by BergWerkGIS** [comment]
@brandonreavis PERFECT! Thanks for your speedy actions.

These changes along with a bit of fiddling with `GDAL_CACHEMAX`,  `memoryLimit` and `NUM_THREADS` brought the processing time of a problematic file from +2hrs down to about 7 minutes.
