### ISSUE TITLE
gdal.open w create options append & update

### ISSUE THREAD

**Issue by kingbin** [naturalatlas/node-gdal#122]
I've tried multiple ways to create an ESRI shapefile with append & update options passed in when opening a KML. My KML has multiple polygons as well as a couple lines named the same. I need to combine identical geometry types in separate files. I'm also trying to cleanup invalid geometries. I believe I've got a working solution using node-spatialite but curious if there was any solution using node-gdal. Thanks for any help from @kingbin & @onehundredpercenttexan 

    var fs  = require('fs-extra')
      , path  = require('path')
      , logger = require(__base+'/classes/logger.js')
      , gdal = require('gdal');

    try{
      uploadedFile = path.resolve(uploadedFile);

      gdal.verbose();
      var parsed = path.parse(uploadedFile);
      var outFolder = path.join( parsed.dir, 'tmp', parsed.name );
      fs.ensureDirSync( outFolder );
      logger.info('OUT=> '+outFolder);

      var outDS = gdal.open(outFolder, 'w','ESRI Shapefile',0,0,0,0,["append","update"]);
      var inDS = gdal.open( uploadedFile );
      inDS.layers.forEach(function(layer){

        var outLayer = outDS.layers.create(layer.name, layer.srs, layer.geomType);

        layer.features.forEach(function(feature){
          var myPoly = feature.getGeometry();
          if( !myPoly.isValid() ) {
            logger.warn('Bad Geometry for '+layer.name);
            feature.setGeometry( myPoly.buffer(0,0) );
          }
          outLayer.features.add(feature);
        });

        outLayer.flush();
      });

      outDS.close();
      inDS.close();

**Comment by brianreavis** [comment]
What errors is it giving you? This looks roughly correct. Mind emailing me your KML so I can mess around with it? brian@naturalatlas.com

**Comment by brandonreavis** [comment]
**Creation Options**
Creation options could perhaps use a bit more documentation, but they correspond to the driver dataset creation options listed here: http://www.gdal.org/drv_shapefile.html and not ogr2ogr options. Since there aren't any for the shapefile driver you can omit them. If there were options you could pass them like: 
```
var options = ["OPTION_NAME=value"];
// or
var options = { OPTION_NAME = "value" };
```

**Open Mode**
`-update` is accomplished using the open mode `r+` instead of `r`
`-append` means that instead of using `outDS.layers.create` you would get an existing layer if it exists and then add features to it. (`outDS.layers.get()`)

**Adding features to layers**
To add features to layers in GDAL, the feature should be created for the particular layer they are being added to. Sometimes it works to use the source feature if the layer definition is exactly the same, but its best not to rely on that
```
    layer.features.forEach(function(srcFeature){
      var dstFeature = new gdal.Feature(outLayer);
      var myPoly = src_feature.getGeometry();
      if( myPoly.isValid() ) {
        dstFeature.setGeometry(myPoly);
      } else {
        logger.warn('Bad Geometry for '+layer.name);
        dstFeature.setGeometry( myPoly.buffer(0,0) );
      }
      dstFeature.fields.set(srcFeature.fields.toObject());
      outLayer.features.add(dstFeature);
    });
```
