### ISSUE TITLE
Registering additional drivers

### ISSUE THREAD

**Issue by JesseGIS** [naturalatlas/node-gdal#171]
I'm very new to both node and gdal so sorry for the noob question.  How do I go about registering additional drivers?  Specifically I'd like to add support for Mssqlspatial and possibly Postgres/PostGIS and some ESRI formats (file geodb, sde).

I'm using Windows8, Git Bash

**Comment by jwoyame** [comment]
Jesse and I were able to figure it out. For the benefit of everyone else, here's how to add a driver, and in particular how to get SQL Server working.

The ultimate goal when adding a format is to get the C++ driver compiled into the main `gdal.node` binary. This binary is a native addon that you `require` from JavaScript to work with GDAL/OGR.

The OGR driver you want to include has to be compiled to a lib file (e.g. `libgdal_ogr_mssqlspatial_frmt.lib`), which is then linked into the `gdal.node` binary.

This C++ build process is handled behind the scenes by node-gyp, using instructions in .gyp files. We need to create the gyp instructions to compile the SQL Server driver and its supporting code.

#### 1. Include the OGR format "mssqlspatial"
The script `deps/libgdal.sh` downloads GDAL to `deps/libgdal/gdal/`. If you look in that directory, the needed driver is a set of C++ files in `ogr/ogrsf_frmts/mssqlspatial`.

The C++ files for different drivers are referenced in the .gyp files found in `deps/gyp-formats`. You can see there is no gyp for ogr_mssqlspatial. Instead of writing the build instructions manually, the `libgdal.sh` script can do it for you. Just open the script, add `mssqlspatial` to the `OGR_FORMATS` string, and run it.

There is now an `ogr_mssqlspatial.gyp` file, that will produce the build target `libgdal_ogr_mssqlspatial_frmt.lib`. `libgdal_formats.gypi` has also been updated to reference this new .gyp. If you try to compile the `gdal.node` binary now, the .lib will be linked in, but you will get linker errors.

#### 2. Include ODBC
The SQL Server driver calls functions from `gdal/port/cp_odbc.h`, but they are defined in `gdal/port/cpl_odbc.cpp`, which is not among the files that are compiled for node-gdal. If you look at `deps/libgdal/libgdal.gyp`, all of the .cpp files from the `port` folder are included in the sources, but `cpl_odbc.cpp` is commented out. This code also relies on `odbccp32.lib`. You can include both on Windows (~line 300):

```gyp
			"conditions": [
				["OS == 'win'", {
					"sources": [
						"gdal/port/cpl_odbc.cpp"
					],
					"link_settings": {
						"libraries": [
							"-lws2_32.lib",
							"-lodbccp32.lib"
						]
					}
				}]
			],
```

If you have Visual Studio 2015 you will experience an [incompatibility issue with odbccp32.lib](https://connect.microsoft.com/VisualStudio/feedback/details/1134693/vs-2015-ctp-5-c-vsnwprintf-s-and-other-functions-are-not-exported-in-appcrt140-dll-breaking-linkage-of-static-libraries) (_"unresolved external symbol _vsnwprintf_s"_), so include `"-llegacy_stdio_definitions.lib"` as well. (Anyone know how to test for VS 2015 in a .gyp file?)

#### 4. Test it
```javascript
var gdal = require("gdal");
console.log(gdal.drivers.getNames());
// should see MSSQLSpatial in the list
```

#### 5. Use it
```javascript
var dataset = gdal.open("MSSQL:server=.\\SQLEXPRESS;database=xxx;trusted_connection=yes");
dataset.layers.forEach(function(layer, i) {
	console.log("layer " + (i+1) + ": " + layer.name);
});
```

**Comment by jwoyame** [comment]
Left off step 3: Build it.

npm install --build-from-source --msvs_version=2013

**Comment by JesseGIS** [comment]
Thanks so much!

**Comment by WGPSenshi** [comment]
Took me a while to get it work using the latest node-gdal on Windows. Then again, I am a complete layman.

Instead of running
`npm install --build-from-source --msvs_version=2013`
I had to run
`npm build node_modules/gdal --build-from-source`
to ensure node-gdal gets properly rebuilt (have the 2015 build tools).
The other steps still are true (thank MS for adding bash to Win10), though some of the libgdal.gpy changes already have been merged into the newer node-gdal versions (the "-llegacy_stdio_definitions.lib" still has to be added to the links->libraries section for VS 2015 users) .

Also: Tried it with Node 7, ran into a variety of issues, so I downgraded to 6.x .
