### ISSUE TITLE
Gdal.open() and postgresSQL

### ISSUE THREAD

**Issue by xyan12345** [naturalatlas/node-gdal#178]
Hi, i am trying to use Gdal to open postgres’s table with Gdal.open function. I have the data table on postgres sql .I can see the table and open it manually, but i can not open it with gdal.open(). Can i access it with Gdal.open like following :

 var dataset = gdal.open('ogrgeojson',mode = 'r',"PG:dbname='udot' user='postgres'           password='hi123456' host='localhost:5433'");

I am pretty sure that i can access it with following command line:

 ogr2ogr -f "PostgreSQL" "PG:dbname=udot user=postgres password=hi123456 host=localhost port=5433"  /Users/../Desktop/project/Routes.json
( this is how i upload file with my terminal by cammand line ) 

However, ‘Gdal.open’ does not work well with that line of code. 

Does anyone have any idea? Did anyone have similar problem?

Thanks!

**Comment by brianreavis** [comment]
We unfortunately don't currently have postgres support added to the bundled GDAL. That issue is being tracked at #20 and #132. If you need it currently, I'd recommend following the instructions in the readme about using node-gdal with the system's copy of GDAL which is bound to have postgres support.
```
npm install gdal --build-from-source --shared_gdal
```

**Comment by xyan12345** [comment]
@brianreavis Thank you so much! that is really helpful! 

appreciate it!
