### ISSUE TITLE
Can not parse .jp2 file.

### ISSUE THREAD

**Issue by taozi0818** [naturalatlas/node-gdal#226]
This library don't support for .jp2 file.It hasn't JPEG-2000 driver.

Use command to parse them or translate them into other format, eg: `.tiff`.

If your OS is MacOS, you must use `brew install gdal2 --with-complete` to install gdal.

**Comment by weagle08** [comment]
node-gdal does not support jp2k out of the box. you can add support for this by getting one of the supported jp2k libraries, i like the one [HERE](https://www.extensis.com/support/developers) because you can add jp2k and mrsid support. You will have to update the binding.gyp file and add the correct format gyp files. You will need to know some about adding formats to gdal and how to set up gyp files. I don't have time to go over this completely right now, but look into adding supported formats to gdal builds to get you started.

**Comment by weagle08** [comment]
There are licensing issues as to why some formats are not supported out of the box
